app/routes.py
import os
import config
from . import db, util, extractors, paths
from .image import clip, binpack, make_pack, get_dimensions, rect_to_points, rotate_image, make_seamless, trim
from flask import Blueprint, abort, request, render_template, jsonify, send_from_directory, session, redirect, url_for

bp = Blueprint('main', __name__)

@bp.route('/')
def index():
    return redirect(url_for('main.clips'))

@bp.route('/clips')
def clips():
    return render_template('clips.html',
            clips=db.all_clips())

@bp.route('/clips.json')
def clips_json():
    return jsonify(clips=list(db.all_clips()))

@bp.route('/sources', methods=['GET', 'POST'])
def sources():
    if request.method == 'GET':
        return render_template('sources.html',
                sources=db.all_sources())
    else:
        data = request.get_json()
        url = data['img_url']
        fname = util.slugify(os.path.split(url)[-1])
        outpath = paths.source(fname)
        util.download(url, outpath)
        size = get_dimensions(outpath)
        id = db.add_source(source_name=fname, size=size, **data)
        db.save()
        return jsonify(success=True, id=id)

@bp.route('/edit/<source_id>', methods=['GET', 'POST'])
def edit(source_id):
    source = db.get_source(source_id)
    if source is None:
        abort(404)
    if request.method == 'POST':
        updates = request.get_json()
        for key, val in updates.items():
            source[key] = val
        db.save()
        return jsonify(success=True)
    else:
        return render_template('source_editor.html',
                id=source['id'],
                name=source['name'],
                tags=source['tags'],
                src=source['src'],
                size=source['size'],
                attribution=source['attribution'],
                clips=[db.get_clip(id) for id in source['clips']])


@bp.route('/img/<path:subpath>')
def image(subpath):
    subdir, fname = os.path.split(subpath)
    return send_from_directory(os.path.join('..', config.IMAGES_DIR, subdir), fname)

@bp.route('/clip', methods=['POST'])
def clip_image():
    data = request.get_json()
    outpath = paths.clip(data['clip_name'])
    points = [tuple(pt) for pt in data['points']]
    source = db.get_source(data['source_id'])
    im = clip(
        paths.source(source['name']),
        points)
    im.save(outpath)
    if 'clip_id' in data:
        clip_data = db.get_clip(data['clip_id'])
        clip_data['name'] = data['clip_name']
        clip_data['points'] = points
    else:
        db.add_clip(data['source_id'], data['clip_name'], points, surface=None)
    db.save()
    return jsonify(success=True,
            path=paths.clip(data['clip_name'], external=True))

@bp.route('/surface', methods=['POST'])
def clip_surface():
    data = request.get_json()
    outpath = paths.clip(data['clip_name'])
    points = rect_to_points(data['rect'])
    source = db.get_source(data['source_id'])
    im = clip(
        paths.source(source['name']),
        points)
    im = trim(rotate_image(im, -data['rect']['rot'])) # Unapply rotation to get rect
    if data['edge_size'] > 0:
        im = make_seamless(im, ['left', 'top'], data['edge_size'], data['fade_size'])
    im.save(outpath)
    surface = dict(edge_size=data['edge_size'], fade_size=data['fade_size'], rect=data['rect'])
    if 'clip_id' in data:
        clip_data = db.get_clip(data['clip_id'])
        clip_data['name'] = data['clip_name']
        clip_data['points'] = points
        clip_data['surface'] = surface
    else:
        db.add_clip(data['source_id'], data['clip_name'], points, surface=surface)
    db.save()
    return jsonify(success=True,
            path=paths.clip(data['clip_name'], external=True))


@bp.route('/packs')
def packs():
    return render_template('packs.html',
            packs=db.all_packs())

@bp.route('/pack', methods=['POST'])
def pack_clips():
    data = request.get_json()

    clips = []
    for clip_id in session.get('pack', []):
        clip = db.get_clip(clip_id)
        if clip is not None:
            outpath = paths.clip(clip['name'])
            clips.append({
                'id': clip_id,
                'points': clip['points'],
                'path': outpath,
            })

    if clips:
        outpath = paths.pack(data['pack_name'])
        positioned_clips = binpack(clips, data['max_side'])

        pack_clips = []
        for clip in positioned_clips:
            clip_ = db.get_clip(clip['id'])
            path = paths.clip(clip_['name'])
            pack_clips.append(
                dict(path=path, **clip))

        im = make_pack(pack_clips)
        im.save(outpath)
        pack = db.add_pack(data['pack_name'], positioned_clips)
        db.save()
        return jsonify(success=True,
                id=pack['id'],
                path=paths.pack(data['pack_name'], external=True))
    else:
        return jsonify(success=False)

@bp.route('/pack/cart', methods=['GET', 'POST', 'DELETE'])
def pack_cart():
    if 'pack' not in session:
        session['pack'] = []

    # Return the current pack cart
    if request.method == 'GET':
        pack = [db.get_clip(clip_id) for clip_id in session.get('pack', [])]
        return jsonify(pack=pack)

    data = request.get_json()

    # Remove a clip from the pack cart
    if request.method == 'DELETE':
        clip_id = data.get('clip_id')
        if clip_id is not None and clip_id in session['pack']:
            session['pack'].remove(clip_id)
            session.modified = True

    else:
        # Reset the pack cart
        if data.get('reset'):
            session['pack'] = []

        # Add a clip to the pack cart
        else:
            clip_id = data.get('clip_id')
            if clip_id is not None and clip_id not in session['pack']:
                session['pack'].append(clip_id)
                session.modified = True

    # Return the current pack cart
    pack = [db.get_clip(clip_id) for clip_id in session.get('pack')]
    return jsonify(success=True, pack=pack)

@bp.route('/pack/<pack_id>', methods=['GET', 'POST'])
def edit_pack(pack_id):
    pack = db.get_pack(pack_id)
    if pack is None: abort(404)

    if request.method == 'GET':
        clips = []
        for clip in pack['clips']:
            clip_ = db.get_clip(clip['id'])
            clips.append(dict(name=clip_['name'], **clip))
        return render_template('pack.html', pack=pack, clips=clips)
    else:
        data = request.get_json()
        outpath = paths.pack(pack['name'])
        for clip in data['clips']:
            clip['path'] = paths.clip(clip['name'])
        im = make_pack(data['clips'])
        im.save(outpath)
        clips = [{
            'id': clip['id'],
            'size': clip['size'],
            'pos': clip['pos'],
            'rot': clip['rot'],
        } for clip in data['clips']]
        db.update_pack(pack_id, clips)
        db.save()
        return jsonify(success=True)

@bp.route('/search')
def search():
    query = request.args.get('query', '')
    sources = request.args.get('sources', '').split(',')

    results = []
    if query:
        for source in sources:
            search_fn = extractors.sources.get(source)
            if search_fn:
                results += search_fn(query)

    # Check if any of these have already been saved
    existing_img_urls = {s['url']: s['id'] for s in db.all_sources()}
    for result in results:
        if result['url'] in existing_img_urls:
            result['saved'] = True
            result['id'] = existing_img_urls[result['url']]

    return render_template('search.html',
            results=results, query=query,
            sources=[(src, src in sources) for src in extractors.sources.keys()])

app/templates/clip_editor.html
{% extends 'layout.html' %}
{% from "items.html" import clip_item %}

{% block content %}
<div class="editor">
    <div class="editor-left">
        <div id="stage"></div>
        <table class="details">
            <tr>
                <td>Name</td><td>{{name}}</td>
            </tr>
            <tr>
                <td>Source</td><td>{{src}}</td>
            </tr>
            <tr>
                <td>Size</td><td>{{size}}</td>
            </tr>
            <tr>
                <td>Attribution</td><td>{{attribution}}</td>
            </tr>
            <tr class="details-tags">
                <td>Tags</td><td><input id="tags" type="text" value="{{tags}}" /></td>
            </tr>
        </table>
    </div>
    <div class="editor-right">
        <input type="text" placeholder="Clip name" id="clip-name-input" />
        <div class="clips">
            <div class="clip-add">+</div>
            {% for clip in clips|reverse %}
                {{ clip_item(clip) }}
            {% endfor %}
        </div>
    </div>
</div>
<script type="text/javascript">
const SOURCE_ID = "{{id}}";
const SOURCE_NAME = "{{name}}";
const CLIPS = {{clips|reverse|list|tojson}};
</script>
<script type="module" src="/static/js/clip.editor.js"></script>
<script type="module" src="/static/js/pack_cart.js"></script>
{% endblock %}

app/templates/clips.html
{% extends 'layout.html' %}
{% from "items.html" import clip_item %}

{% block content %}
<div id="browser">
    <input id="filter" type="text" placeholder="Search" autofocus />
    <div id="clip-browser-preview"><img src="" /></div>
    <div id="browser-items">
        {% for clip in clips %}
            {{ clip_item(clip, editable=True) }}
        {% endfor %}
    </div>
</div>

<script type="module" src="/static/js/pack_cart.js"></script>
<script src="/static/js/listing.js"></script>
<script>
setupFilter(
  '#filter',
  (el) => [el.dataset.name.toLowerCase()]);
setupPreviews();
</script>
{% endblock %}

app/templates/edit.html
{% extends 'layout.html' %}

{% block content %}
<div class="editor">
    <div class="editor-left">
        <div id="stage"></div>
        <table class="details">
            <tr>
                <td>Name</td><td>{{name}}</td>
            </tr>
            <tr>
                <td>Source</td><td>{{src}}</td>
            </tr>
            <tr>
                <td>Attribution</td><td>{{attribution}}</td>
            </tr>
            <tr>
                <td>Tags</td><td><input id="tags" type="text" value="{{tags}}" /></td>
            </tr>
        </table>
    </div>
    <div class="editor-right">
        <input type="text" placeholder="Clip name" id="clip-name-input" />
        <div class="clips">
            <div class="clip-add">+</div>
            {% for clip in clips|reverse %}
                <div class="clip" data-id="{{clip.id}}">
                    <div class="clip-preview">
                        <img src="/img/clips/{{clip.name}}.png">
                    </div>
                    <div class="clip-name">{{clip.name}}</div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
<script type="text/javascript">
const sourceId = "{{id}}";
const sourceName = "{{name}}";
const clips = {{clips|reverse|list|tojson}};
</script>
<script type="module" src="/static/js/editor.js"></script>
{% endblock %}

app/templates/editor.html
{% extends 'layout.html' %}
{% from "items.html" import clip_item %}

{% block content %}
<div class="editor">
    <div class="editor-left">
        <div id="stage"></div>
        <table class="details">
            <tr>
                <td>Name</td><td>{{name}}</td>
            </tr>
            <tr>
                <td>Source</td><td>{{src}}</td>
            </tr>
            <tr>
                <td>Size</td><td>{{size}}</td>
            </tr>
            <tr>
                <td>Attribution</td><td>{{attribution}}</td>
            </tr>
            <tr class="details-tags">
                <td>Tags</td><td><input id="tags" type="text" value="{{tags}}" /></td>
            </tr>
        </table>
    </div>
    <div class="editor-right">
        <input type="text" placeholder="Clip name" id="clip-name-input" />
        <div class="clips">
            <div class="clip-add">+</div>
            {% for clip in clips|reverse %}
                {{ clip_item(clip) }}
            {% endfor %}
        </div>
    </div>
</div>
<script type="text/javascript">
const SOURCE_ID = "{{id}}";
const SOURCE_NAME = "{{name}}";
const CLIPS = {{clips|reverse|list|tojson}};
</script>
<script type="module" src="/static/js/editor.js"></script>
<script type="module" src="/static/js/pack.js"></script>
{% endblock %}

app/templates/index.html
{% extends 'layout.html' %}

{% block content %}
<div class="editor">
    <div id="stage"></div>
    <div class="clips"></div>
    <img id="clipped" />
</div>
<script type="module" src="/static/js/main.js"></script>
{% endblock %}

app/templates/items.html
{% macro clip_item(clip, editable=False) -%}
    <div class="clip" data-id="{{clip.id}}" data-name="{{clip.name}}" data-source="{{clip.source}}">
    <div class="clip-in-pack"><img src="/static/assets/in_pack.png" /></div>
    <div class="clip-preview">
        <img src="/img/clips/{{clip.name}}.png">
    </div>
    <div class="clip-name">{{clip.name}}</div>
    <div class="clip-menu">
        <div></div>
        <div>
            {% if editable %}<a href="/edit/{{clip.source}}"><img src="/static/assets/image.png" /></a>{% endif %}
            <a class="rem-from-pack"><img src="/static/assets/rem_from_pack.png" /></a>
            <a class="add-to-pack"><img src="/static/assets/add_to_pack.png" /></a>
        </div>
    </div>
</div>
{%- endmacro %}

{% macro source_item(item) -%}
<div class="clip" data-id="{{item.id}}" data-name="{{item.name}}" data-tags="{{item.tags}}">
    <a href="/edit/{{item.id}}" class="browser-item-link"></a>
    <div class="clip-preview">
        <img src="/img/sources/{{item.name}}">
    </div>
    <div class="clip-name">{{item.name}}</div>
</div>
{%- endmacro %}

{% macro pack_item(item) -%}
<div class="clip" data-id="{{item.id}}" data-name="{{item.name}}">
    <a href="/pack/{{item.id}}" class="browser-item-link"></a>
    <div class="clip-preview">
        <img src="/img/packs/{{item.name}}.png">
    </div>
    <div class="clip-name">{{item.name}}</div>
</div>
{%- endmacro %}

{% macro search_result(item) -%}
<div class="search-result {{'selected' if item.saved}}" data-src="{{item.src}}" data-url="{{item.url}}" data-attribution="{{item.attribution}}">
    <div class="search-result-preview" >
        <img src="{{item.thumb}}">
    </div>
    <div class="search-result-details">
        <div>{{item.attribution}}</div>
        {% if item.saved %}
            <a class="view-result" href="/edit/{{item.id}}">View</a>
        {% else %}
            <div class="save-result">Save</div>
        {% endif %}
    </div>
</div>
{%- endmacro %}

app/templates/layout.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Texture Editor</title>
  <link rel="stylesheet" type="text/css" href="/static/style.css">
</head>
<body>
    <main>
        <header>
            <a href="{{ url_for('main.clips') }}">Clips</a>
            <a href="{{ url_for('main.packs') }}">Packs</a>
            <a href="{{ url_for('main.sources') }}">Sources</a>
            <a href="{{ url_for('main.search') }}">Search</a>
        </header>
        <div class="status-notification">Ok</div>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

app/templates/pack.html
{% extends 'layout.html' %}
{% from "items.html" import clip_item %}

{% block content %}
<div id="clips-popup" class="popup"></div>
<div id="pack-preview">
    <img src="/img/packs/{{pack.name}}.png">
</div>
<div class="editor">
    <div class="editor-left">
        <div id="stage" class="stage"></div>
        <table class="details">
            <tr>
                <td>Name</td><td>{{pack.name}}</td>
            </tr>
            <tr>
                <td>Clips</td><td>
                    {% for clip in clips %}
                        <a class="pack-included-clip" href="/edit/{{clip.id}}">{{clip.name}}</a>
                    {% endfor %}
                </td>
            </tr>
        </table>
    </div>
</div>
<script type="text/javascript">
const PACK_ID = "{{pack.id}}";
const PACK_NAME = "{{pack.name}}";
const CLIPS = {{clips|list|tojson}};
</script>
<script type="module" src="/static/js/pack.editor.js"></script>
{% endblock %}

app/templates/packs.html
{% extends 'layout.html' %}
{% from "items.html" import pack_item %}

{% block content %}
<div id="browser">
    <input id="filter" type="text" placeholder="Search" autofocus />
    <div id="clip-browser-preview"><img src="" /></div>
    <div id="browser-items">
        {% for item in packs %}
            {{ pack_item(item) }}
        {% endfor %}
    </div>
</div>
<script src="/static/js/listing.js"></script>
<script>
setupFilter(
  '#filter',
  (el) => [el.dataset.name.toLowerCase()]);
setupPreviews();
</script>
{% endblock %}

app/templates/search.html
{% extends 'layout.html' %}
{% from "items.html" import search_result %}

{% block content %}
<div id="browser">
    <input type="text" placeholder="Search" value="{{query}}" autofocus />
    <div class="sources">
        {% for source, selected in sources %}
            <div>
                <input id="{{source}}" type="checkbox" {{'checked' if selected}} /><label for="{{source}}">{{ source }}</label>
            </div>
        {% endfor %}
    </div>
    <div id="browser-items">
        {% for item in results %}
            {{ search_result(item) }}
        {% endfor %}
    </div>
</div>
<script type="module" src="/static/js/search.js"></script>
{% endblock %}

app/templates/source_editor.html
{% extends 'layout.html' %}
{% from "items.html" import clip_item %}

{% block content %}
<div class="editor">
    <div class="editor-left">
        <div class="stage-tabs">
            <button class="stage-tabs--clip">C</button>
            <button class="stage-tabs--surface">S</button>
        </div>
        <div id="stage" class="stage"></div>
        <table class="details">
            <tr>
                <td>Name</td><td>{{name}}</td>
            </tr>
            <tr>
                <td>Source</td><td>{{src}}</td>
            </tr>
            <tr>
                <td>Size</td><td>{{size}}</td>
            </tr>
            <tr>
                <td>Attribution</td><td>{{attribution}}</td>
            </tr>
            <tr class="details-tags">
                <td>Tags</td><td><input id="tags" type="text" value="{{tags}}" /></td>
            </tr>
        </table>
    </div>
    <div class="editor-right">
        <input type="text" placeholder="Clip name" id="clip-name-input" />
        <div class="clips">
            <div class="clip-add">+</div>
            {% for clip in clips|reverse %}
                {{ clip_item(clip) }}
            {% endfor %}
        </div>
    </div>
</div>
<script type="text/javascript">
const SOURCE_ID = "{{id}}";
const SOURCE_NAME = "{{name}}";
const CLIPS = {{clips|reverse|list|tojson}};
</script>
<script type="module" src="/static/js/source.editor.js"></script>
<script type="module" src="/static/js/pack_cart.js"></script>
{% endblock %}

app/templates/sources.html
{% extends 'layout.html' %}
{% from "items.html" import source_item %}

{% block content %}
<div id="browser">
    <input id="filter" type="text" placeholder="Search" autofocus />
    <div id="clip-browser-preview"><img src="" /></div>
    <div id="browser-items">
        {% for item in sources %}
            {{ source_item(item) }}
        {% endfor %}
    </div>
</div>
<script src="/static/js/listing.js"></script>
<script>
setupFilter(
  '#filter',
  (el) => [el.dataset.name.toLowerCase(), el.dataset.tags.toLowerCase()]);
setupPreviews();
</script>
{% endblock %}